from .workflow_stats_node import WORKFLOWSTAT_CLASS_MAPPINGS, WORKFLOWSTAT_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(WORKFLOWSTAT_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WORKFLOWSTAT_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']